### ISSUE TITLE
Code review comments

### ISSUE THREAD

**Issue by ryan-airwallex** [blandon12/rpn-calculator#1]
1. Why don't you use CommandLineRunner?
2. What's the definition of ExternalCommand and InternalCommand? What's the purpose of having this abstraction?
3. Stack is a Java 1.0 thing, it's recommended to use Deque implementations since Java 6/7.
4. Divide 0
5. Square function doesn't handle negative inputs, it also converts a BigDecimal back to Double when calculating the square root.
new BigDecimal(sqrt(firstNumber.doubleValue()), MathContext.DECIMAL128)
                .setScale(15, RoundingMode.HALF_UP)
                .stripTrailingZeros();
6. Don't really like the undo implementation.

**Comment by blandon12** [comment]
Hi Ryan,

Many thanks for your code review. Regard point#1 and point#3, I agree with you. Both CommandLineRunner and Deque will be the better options here. Also, appreciate correct me in point#4 and point#5. I should have handled them in a proper way at least avoiding such an entry-level mistake.

In response the point#2, we would say ExternalCommand is the command or keyword that users input, i.e. *, sqrt or any numbers, while InternalCommand is stack operations including "Pop" and "Push". ExternalCommand and InternalCommand could be a one-to-many relationship as each user input could involve a few stack operations. I did create interface for both and try to follow SOLID principles, "open / close principle". It will be easier to extend other types of ExternalCommand if it's needed although it seems a bit of redundant here.

As mentioned in the Description section in README file, I understand the undo implementation isn't ideal. That will be much appreciated if you could advise me any better solution to it?

Thanks again for your time and efforts on the review and feedbacks.

Regards,
Chunxin

**Comment by ryan-airwallex** [comment]
Hi Chunxin, 

You are welcome. I'd usually suggest to use the Memento pattern to implement History Backtracking requirements. Just imaging if I ask you to add a new "redo" function to the requirements. What will happen to your implementation? You will probably have to refactor the entire history repository implementation into to achieve the functionality. 

Cheers,
Ryan

**Comment by blandon12** [comment]
Thanks for your quick response. Yes, the Memento pattern is a much better solution to both undo and redo functions.
